name: release-publish

on:
  push:
    branches: [main]
    paths-ignore:
      # Ignore all the files that are modified in the action
      - "VERSION"

concurrency:
  group: church-offering-main
  cancel-in-progress: true

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: simple

  publish:
    needs: release
    if: ${{ needs.release.outputs.release_name }}
    runs-on: ubuntu-latest
    outputs:
      release_name: ${{ needs.release.outputs.release_name }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: "Dockerfile"
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.release.outputs.release_name }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
